spring.application.name=jobapplication


spring.datasource.url=jdbc:postgresql://localhost:5432/jobpost
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver.class.name=org.postgresql.Driver